language: go

env:
  - GIMME_OS=linux GIMME_ARCH=amd64 GIMME_GO_VERSION=1.2
  - GIMME_OS=linux GIMME_ARCH=amd64 GIMME_GO_VERSION=1.3
  - GIMME_OS=linux GIMME_ARCH=amd64 GIMME_GO_VERSION=1.4

install:
  - go get -d -t -v ./...

script:
  - go test -v ./...
